export const POSTS = {
    POSTS_FETCH_REQUESTED : "POSTS_FETCH_REQUESTED",
    POSTS_FETCH_SUCCESS: "POSTS_FETCH_SUCCESS",
    POSTS_FETCH_FAILD: "POSTS_FETCH_FAILD",

    POST_FETCH_REQUESTED: "POST_FETCH_REQUESTED",
    POST_SET_CURRENT_ID: "POST_SET_CURRENT_ID",
    POST_FECTH_SUCCESS: "POST_FECTH_SUCCESS",
    POST_FETCH_FAILD: "POST_FETCH_FAILD"
}