/*
This const used for All Posts Actions!
*/
export const POSTS = {
    // FETCH AND SHOW!
    FETCH_POSTS_REQUEST: "FETCH_POSTS_REQUEST",
    FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
    FETCH_POSTS_ERROR: "FETCH_POSTS_ERROR",

    // CREATES
    CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
    CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
    CREATE_POST_ERROR: "CREATE_POST_ERROR",

    // UPDATES
    UPDATE_POST_REQUEST: "UPDATE_POST_REQUEST",
    UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
    UPDATE_POST_ERROR: "UPDATE_POST_ERROR",

    // DELETE
    DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
    DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
    DELETE_POST_ERROR: "DELETE_POST_ERROR",

    // DETAIL
    FETCH_POST_REQUEST: "FETCH_POST_REQUEST",
    FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
    FETCH_POST_ERROR: "FETCH_POST_ERROR",
};

/**
 * This Const used for handle authentication
*/
export const AUTH = {
    SET_LOGIN: "SET_LOGIN"
}